import type { Metadata } from 'next';
import './globals.css';
import { montserrat, roboto } from './utils/fonts';
import Header from './components/Header/header';
import Footer from './components/Footer/footer';

export const metadata: Metadata = {
	title: 'Travelo',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${montserrat.variable} ${roboto.variable}`}>
			<body>
				<>
					<Header />
					{children}
					<Footer />
				</>
			</body>
		</html>
	);
}
