import type { Metadata } from 'next';
import './globals.css';
import { montserrat, roboto } from './utils/fonts';

export const metadata: Metadata = {
	title: 'Travelo',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" className={`${montserrat.variable} ${roboto.variable}`}>
			<body>{children}</body>
		</html>
	);
}
