import type { Metadata } from 'next';
import { montserrat, roboto } from '../utils/fonts';
import Header from '../components/Layout/Header/header';

export const metadata: Metadata = {
	title: 'Travelo',
	description: 'Generated by create next app',
};

export default function LoginLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<>
			<Header />
			{children}
		</>
	);
}
